In [1]:
# Plots
import matplotlib.pyplot as plt

# Numerical arrays
import numpy as np

# Data frames
import pandas as pd

# Shuffle
import random

#Statistics
import scipy.stats as ss

In [2]:
%%html
<style id=hide>div.input{display:none;}</style>
<button type="button" 
onclick="var myStyle = document.getElementById('hide').sheet;myStyle.insertRule('div.input{display:inherit !important;}', 0);">
Show inputs</button>

In [3]:
%%html
<div class="alert alert-block alert-info">
<b>Tip:</b> Use blue boxes (alert-info) for tips and notes. 
</div>

<div class="alert alert-block alert-warning">
Warning: Use Yellow for a warning that might need attention.
</div>

<div class="alert alert-block alert-success">
Green box can be used to show some positive such as the successful execution of a test or code.
</div>

<div class="alert alert-block alert-danger">
Red boxes can be used to alert users to not delete some important part of code etc. 
</div>

In [4]:
from IPython.display import HTML, display

def set_background(color):
    script = ("var cell = this.closest('.code_cell');"
              "var editor = cell.querySelector('.input_area');"
              "editor.style.background='{}';" 
              "this.parentNode.removeChild(this)"
             ).format(color)
    display(HTML('<img src onerror="{}">'.format(script)))
    
    
set_background('#E9FDFF')

In [5]:
class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

In [6]:
print(color.BOLD + color.BLUE + ""'''Task 1'''"" + color.END)

Task 1


# Tasks

Machine Learning and Statistics

Winter 2023/2024

by Ian McLoughlin

#### <font color='289C4E'>Table of contents<font><a class='anchor' id='top'></a>
- [Task 1](#1)
- [Task 2](#2)
- [Task 3](#3)
- [Task 4](#4)
- [Task 5](#5)
***

<h2 align="center"> <font color='navy'>Task 1</font></h2>

In [8]:
%%html
<div class="alert alert-block alert-info">
Square roots are difficult to calculate. In Python, you typically use the power operator (a double asterisk) or a package such as <b>math</b>. In this task, you should write a function <b>sqrt(x)</b> to approximate the square root of a floating point number x without using the power operator or a package.
</div>

In [9]:
%%html
<div class="alert alert-block alert-info">
Rather, you should use the Newton’s method. Start with an initial guess for the square root called $z_0$. You then repeatedly improve it using the following formula, until the difference between some previous guess <b>$z_i$</b> and the next <b>$z_{i+1}$</b> is less than some threshold, say 0.01
</div>

$$ z_{i+1} = z_1 - \frac{z_i × z_i - x}{2z_i} $$

***
## Task 1

> Square roots are difficult to calculate. In Python, you typically use the power operator (a double asterisk) or a package such as 'math'. In this task, you should write a function 'sqrt(x)' to approximate the square root of a floating point number x without using the power operator or a package.

> Rather, you should use the Newton’s method. Start with an initial guess for the square root called $z_0$. You then repeatedly improve it using the following formula, until the difference between some previous guess $z_i$ and the next $z_{i+1}$ is less than some threshold, say 0.01

$$ z_{i+1} = z_1 - \frac{z_i × z_i - x}{2z_i} $$
***

In [10]:
def sqrt(x):
    # Initial guess for the square root
    z = x /4.0

    # Loop until we are accurate enough
    #while (z could be improved):
    for i in range(100):
        # Newton's method for a better approximation
        z = z - (((z * z) - x)/(2 * z))
        
    # z should now be a good a good approximation for the square root
    return z

In [11]:
        # Test the function on 3    
        sqrt(3)

1.7320508075688774

In [12]:
        # Check Python's value for square root of 3    
        3**0.5

1.7320508075688772

In [13]:
print('\x1B[1;37m'+"----------------------------------------------------------------------------------------------------------------------------")

----------------------------------------------------------------------------------------------------------------------------


### <font color='grey'>Notes:<font><a class='anchor' id='top'></a>

***
**1.** The calculation **$z^2 - x$** is exactly zero when **$z$** is the square root of **$x$**. It is greater than zero when $z$ is too bug. It is less than zero when $z$ is too small. Thus $(z^2 - x)^2$ is a good candidate for a cost function.

**2.** The derivative of the numerator $z^2 - x$ with respect to $z$ is $2z$. That is the dominator of the fraction in the formula from the question.
***

<h4 align="center"> <i><font color='gray'>*** End of Task 1 ***</font></i></h4>

<h2 align="center"> <font color='navy'>Task 2</font></h2>

In [14]:
%%html
<div class="alert alert-block alert-info">
Consider the below contingency table based on a survey asking
respondents whether they prefer coffee or tea and whether they
prefer plain or chocolate biscuits.
</div>

In [15]:
%%html
<div class="alert alert-block alert-info">
Use <b>scipy.stats</b> to perform
a <b>chi-squared</b> test to see whether there is any evidence of an association between drink preference and biscuit preference in this
instance.
</div>



# Put Table from q2

In [16]:
# Forty-three Coffee drinkers who preferred Chocolate Biscuit

coffee_chocolate = [['Coffee', 'Chocolate Biscuit']] * 43

# Show

coffee_chocolate

[['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'C

In [17]:
# Fifty-six Tea drinkers who preferred Chocolate Biscuit

tea_chocolate = [['Tea', 'Chocolate Biscuit']] * 56

# Show

tea_chocolate

[['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea',

In [18]:
# Fifty-seven Coffee drinkers who preferred Plain Biscuit

coffee_plain = [['Coffee', 'Plain Biscuit']] * 57

# Show

coffee_plain 

[['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee'

In [19]:
# Forty-five Tea drinkers who preferred Plain Biscuit

tea_plain = [['Tea', 'Plain Biscuit']] * 45

# Show

tea_plain

[['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 

In [20]:
# Raw data, merge the four lists

raw_data = coffee_chocolate + coffee_plain + tea_chocolate + tea_plain

# Show
raw_data

[['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'C

In [21]:
# Shuffle the data

random.shuffle(raw_data)

# Show

raw_data

[['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Tea', 'Chocolate Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Tea', 'Plain Biscuit'],
 ['Coffee', 'Chocolate Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Coffee', 'Plain Biscuit'],
 ['Tea', 'Chocolate Bi

In [22]:
# Zip the list - make the rows columns and the columns rows
# Interchganges the outer and inner lists

drink, biscuit = list(zip(*raw_data))

# Show

drink, biscuit

(('Coffee',
  'Coffee',
  'Tea',
  'Tea',
  'Tea',
  'Coffee',
  'Coffee',
  'Coffee',
  'Coffee',
  'Coffee',
  'Coffee',
  'Coffee',
  'Coffee',
  'Coffee',
  'Coffee',
  'Tea',
  'Tea',
  'Coffee',
  'Coffee',
  'Coffee',
  'Tea',
  'Tea',
  'Coffee',
  'Coffee',
  'Coffee',
  'Coffee',
  'Tea',
  'Coffee',
  'Coffee',
  'Coffee',
  'Coffee',
  'Tea',
  'Coffee',
  'Coffee',
  'Tea',
  'Coffee',
  'Coffee',
  'Coffee',
  'Tea',
  'Coffee',
  'Tea',
  'Tea',
  'Coffee',
  'Coffee',
  'Tea',
  'Tea',
  'Tea',
  'Tea',
  'Coffee',
  'Coffee',
  'Tea',
  'Tea',
  'Coffee',
  'Tea',
  'Coffee',
  'Coffee',
  'Tea',
  'Coffee',
  'Tea',
  'Coffee',
  'Coffee',
  'Coffee',
  'Tea',
  'Tea',
  'Coffee',
  'Tea',
  'Tea',
  'Tea',
  'Tea',
  'Tea',
  'Coffee',
  'Coffee',
  'Tea',
  'Coffee',
  'Tea',
  'Tea',
  'Coffee',
  'Tea',
  'Coffee',
  'Coffee',
  'Tea',
  'Tea',
  'Tea',
  'Coffee',
  'Tea',
  'Tea',
  'Tea',
  'Coffee',
  'Tea',
  'Coffee',
  'Tea',
  'Tea',
  'Tea',
  'Coffee',
 

In [23]:
# Create a data frame

df = pd.DataFrame({'drink': drink, 'biscuit': biscuit})

# Show

df

drink            biscuit
0    Coffee  Chocolate Biscuit
1    Coffee  Chocolate Biscuit
2       Tea      Plain Biscuit
3       Tea      Plain Biscuit
4       Tea      Plain Biscuit
..      ...                ...
196  Coffee  Chocolate Biscuit
197     Tea  Chocolate Biscuit
198     Tea  Chocolate Biscuit
199     Tea      Plain Biscuit
200  Coffee      Plain Biscuit

[201 rows x 2 columns]

### Contingency Table

In [24]:
# Perform Crosstabs Contingency
cross = ss.contingency.crosstab(df['drink'], df['biscuit'])

# Show
cross

CrosstabResult(elements=(array(['Coffee', 'Tea'], dtype=object), array(['Chocolate Biscuit', 'Plain Biscuit'], dtype=object)), count=array([[43, 57],
       [56, 45]]))

In [25]:
# The first variable values and the second
first, second = cross.elements

# Show
first, second

(array(['Coffee', 'Tea'], dtype=object),
 array(['Chocolate Biscuit', 'Plain Biscuit'], dtype=object))

In [26]:
# The counts
cross.count

array([[43, 57],
       [56, 45]])

In [27]:
# Find all rows in df with drink equal to the first value in first
df[df['drink'] == first[0]]

drink            biscuit
0    Coffee  Chocolate Biscuit
1    Coffee  Chocolate Biscuit
5    Coffee  Chocolate Biscuit
6    Coffee  Chocolate Biscuit
7    Coffee  Chocolate Biscuit
..      ...                ...
181  Coffee      Plain Biscuit
182  Coffee      Plain Biscuit
188  Coffee      Plain Biscuit
196  Coffee  Chocolate Biscuit
200  Coffee      Plain Biscuit

[100 rows x 2 columns]

In [28]:
# Find all rows in df with drink equal to the first value in first and biscuit equal to first value in second
df[df['drink'] == first[0]][df['biscuit'] == second[0]]

C:\Users\User\AppData\Local\Temp\ipykernel_31240\753605037.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['drink'] == first[0]][df['biscuit'] == second[0]]


drink            biscuit
0    Coffee  Chocolate Biscuit
1    Coffee  Chocolate Biscuit
5    Coffee  Chocolate Biscuit
6    Coffee  Chocolate Biscuit
7    Coffee  Chocolate Biscuit
8    Coffee  Chocolate Biscuit
9    Coffee  Chocolate Biscuit
12   Coffee  Chocolate Biscuit
13   Coffee  Chocolate Biscuit
14   Coffee  Chocolate Biscuit
17   Coffee  Chocolate Biscuit
18   Coffee  Chocolate Biscuit
19   Coffee  Chocolate Biscuit
24   Coffee  Chocolate Biscuit
27   Coffee  Chocolate Biscuit
32   Coffee  Chocolate Biscuit
33   Coffee  Chocolate Biscuit
35   Coffee  Chocolate Biscuit
36   Coffee  Chocolate Biscuit
52   Coffee  Chocolate Biscuit
54   Coffee  Chocolate Biscuit
55   Coffee  Chocolate Biscuit
57   Coffee  Chocolate Biscuit
59   Coffee  Chocolate Biscuit
64   Coffee  Chocolate Biscuit
70   Coffee  Chocolate Biscuit
83   Coffee  Chocolate Biscuit
89   Coffee  Chocolate Biscuit
93   Coffee  Chocolate Biscuit
102  Coffee  Chocolate Biscuit
106  Coffee  Chocolate Biscuit
111  Coffee  Chocolate Biscuit
116  Coffee  Chocolate Biscuit
118  Coffee  Chocolate Biscuit
119  Coffee  Chocolate Biscuit
130  Coffee  Chocolate Biscuit
133  Coffee  Chocolate Biscuit
144  Coffee  Chocolate Biscuit
146  Coffee  Chocolate Biscuit
151  Coffee  Chocolate Biscuit
157  Coffee  Chocolate Biscuit
177  Coffee  Chocolate Biscuit
196  Coffee  Chocolate Biscuit

In [29]:
# The contingency table
cross.count

array([[43, 57],
       [56, 45]])

In [30]:
# Do the statistics
result = ss.chi2_contingency(cross.count, correction = False)

# Show
result

Chi2ContingencyResult(statistic=3.113937364324669, pvalue=0.07762509678333357, dof=1, expected_freq=array([[49.25373134, 50.74626866],
       [49.74626866, 51.25373134]]))

In [31]:
# The expected frequencies if independent
result.expected_freq

array([[49.25373134, 50.74626866],
       [49.74626866, 51.25373134]])

In [32]:
# Preffered Chocolate Biscuit irrespective of drink
99 / 201

0.4925373134328358

In [33]:
# If no relationship between drink and biscuit,
# then we should have same proportion of Coffee drinkers
# liking Chocolate Biscuit as we have overall

100 * (99 / 201)

49.25373134328358

<h4 align="center"> <i><font color='gray'>*** End of Task 2 ***</font></i></h4>

<h2 align="center"> <font color='navy'>Task 3</font></h2>

In [34]:
%%html
<div class="alert alert-block alert-info">
Perform a <b>t-test</b> on the famous penguins data set to investigate whether there is evidence of a significant difference in the body
mass of male and female gentoo penguins.
</div>

### Independent Sample t-test
***

In [38]:
# Load Penguins Data
df = pd.read_csv('penguins.csv')

# Show the DataFrame
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
3            NaN     NaN  
4         3450.0  FEMALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[344 rows x 7 columns]

In [39]:
# Male body mass
sample_male = df[df['sex'] == 'MALE']['body_mass_g'].to_numpy()

sample_male

array([3750., 3650., 4675., 3800., 4400., 4500., 4200., 3600., 3950.,
       3800., 3550., 3950., 3900., 3900., 4150., 3950., 4650., 3900.,
       4400., 4600., 3425., 4150., 4300., 4050., 3700., 3800., 3750.,
       4400., 4050., 3950., 4100., 4450., 3900., 4150., 4250., 3900.,
       4000., 4700., 4200., 3550., 3800., 3950., 4300., 4450., 4300.,
       4350., 4100., 4725., 4250., 3550., 3900., 4775., 4600., 4275.,
       4075., 3775., 3325., 3500., 3875., 4000., 4300., 4000., 3500.,
       4475., 3900., 3975., 4250., 3475., 3725., 3650., 4250., 3750.,
       4000., 3900., 3650., 3725., 3750., 3700., 3775., 4050., 4050.,
       3300., 4400., 3400., 3800., 4150., 3800., 4550., 4300., 4100.,
       3600., 4800., 4500., 3950., 3550., 4450., 4300., 3250., 3950.,
       4050., 3450., 4050., 3800., 3950., 4000., 3775., 4100., 5700.,
       5700., 5400., 5200., 5150., 5550., 5850., 5850., 6300., 5350.,
       5700., 5050., 5100., 5650., 5550., 5250., 6050., 5400., 5250.,
       5350., 5700.,

In [40]:
# Female body mass
sample_female = df[df['sex'] == 'FEMALE']['body_mass_g'].to_numpy()

sample_female

array([3800., 3250., 3450., 3625., 3200., 3700., 3450., 3325., 3400.,
       3800., 3800., 3200., 3150., 3250., 3300., 3325., 3550., 3300.,
       3150., 3100., 3000., 3450., 3500., 3450., 2900., 3550., 2850.,
       3150., 3600., 2850., 3350., 3050., 3600., 3550., 3700., 3700.,
       3550., 3200., 3800., 3350., 3500., 3600., 3550., 3400., 3300.,
       3700., 2900., 3725., 3075., 2925., 3750., 3175., 3825., 3200.,
       3900., 2900., 3350., 3150., 3450., 3050., 3275., 3050., 3325.,
       3500., 3425., 3175., 3400., 3400., 3050., 3000., 3475., 3450.,
       3700., 3500., 3525., 3950., 3250., 4150., 3800., 3700., 3575.,
       3700., 3450., 3600., 2900., 3300., 3400., 3700., 3200., 3350.,
       3900., 3850., 2700., 3650., 3500., 3675., 3400., 3675., 3325.,
       3600., 3350., 3250., 3525., 3650., 3650., 3400., 3775., 4500.,
       4450., 4550., 4800., 4400., 4650., 4650., 4200., 4150., 4800.,
       5000., 4400., 5000., 4600., 4700., 5050., 5150., 4950., 4350.,
       3950., 4300.,

In [41]:
# t-test

ss.ttest_ind(sample_male, sample_female)

TtestResult(statistic=8.541720337994516, pvalue=4.897246751596224e-16, df=331.0)

<h4 align="center"> <i><font color='gray'>*** End of Task 3 ***</font></i></h4>

<h2 align="center"> <font color='navy'>Task 4</font></h2>

<h6 style="background-color:lightblue"><font color='blue'>Using the famous iris data set, suggest whether the setosa class is easily separable from the other two classes. Provide evidence
for your answer.</font></h6>

In [35]:
%%html
<div class="alert alert-block alert-info">
Using the famous iris data set, suggest whether the setosa class is easily separable from the other two classes. Provide evidence
for your answer.
</div>

<h4 align="center"> <i><font color='gray'>*** End of Task 4 ***</font></i></h4>

<h2 align="center"> <font color='navy'>Task 5</font></h2>

In [36]:
%%html
<div class="alert alert-block alert-info">
Perform Principal Component Analysis on the iris data set, reducing the number of dimensions to two. Explain the purpose
of the analysis and your results.
</div>

<h4 align="center"> <i><font color='gray'>*** End of Task 5 ***</font></i></h4>